#!/usr/bin/env python3
"""Generate docs/guides/user-stories.md from story.json fixtures.

Source of truth is tests/fixtures/models/**/stories/*/story.json plus
tests/fixtures/models/personas.json. Prefer static/fixture/v1 when the same
story id appears under multiple model trees.

Usage:
  python scripts/generate_user_stories_md.py          # write the guide
  python scripts/generate_user_stories_md.py --check  # exit 1 if stale
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tests"))

from stories.catalog import (  # noqa: E402
    collect_canonical_stories,
    validate_story_fixtures,
)

FIXTURES = ROOT / "tests" / "fixtures" / "models"
PERSONAS_PATH = FIXTURES / "personas.json"
GUIDE_PATH = ROOT / "docs" / "guides" / "user-stories.md"
PERSONA_ORDER = ("nubble", "fangore", "taloneth")


def _load_json(path: Path) -> dict[str, Any]:
    import json

    return json.loads(path.read_text(encoding="utf-8"))


def _render_footnotes(story: dict[str, Any]) -> list[str]:
    footnotes = story.get("footnotes") or []
    if not footnotes:
        return []
    lines = ["#### Footnotes", ""]
    narrative = str(story.get("narrative") or "")
    cited = set(re.findall(r"\[\^([A-Za-z0-9_-]+)\]", narrative))
    for i, item in enumerate(footnotes, start=1):
        fid = str(item["id"])
        label = str(item["label"])
        url = str(item["url"])
        note = item.get("note")
        suffix = f" — {note}" if isinstance(note, str) and note.strip() else ""
        if cited:
            # Markdown footnote definition form when narrative uses [^id]
            lines.append(f"[^{fid}]: [{label}]({url}){suffix}")
        else:
            lines.append(f"{i}. [{label}]({url}){suffix}")
    lines.append("")
    return lines


def render_guide(stories: dict[str, dict[str, Any]], personas: dict[str, Any]) -> str:
    lines: list[str] = [
        "<!-- Generated by scripts/generate_user_stories_md.py — do not edit by hand. -->",
        "",
        "# User stories",
        "",
        str(personas["intro"]).rstrip(),
        "",
        "## Personas",
        "",
    ]
    persona_meta = {p["id"]: p for p in personas["personas"]}
    for pid in PERSONA_ORDER:
        p = persona_meta[pid]
        lines.append(f"### {p['name']} — {p['role']}")
        lines.append("")
        lines.append(str(p["bio"]).rstrip())
        lines.append("")

    lines.append("## Running the suite")
    lines.append("")
    lines.append(str(personas["running_suite"]).rstrip())
    lines.append("")
    lines.append("## Models")
    lines.append("")
    lines.append(str(personas["models"]).rstrip())
    lines.append("")

    by_persona: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for story in stories.values():
        by_persona[str(story["persona"])].append(story)

    for pid in PERSONA_ORDER:
        name = persona_meta[pid]["name"]
        lines.append(f"## {name}'s stories")
        lines.append("")
        for story in sorted(by_persona.get(pid, []), key=lambda s: s["id"]):
            lines.append(f"### `{story['id']}` — {story['title']}")
            lines.append("")
            lines.append(str(story["narrative"]).rstrip())
            lines.append("")
            lines.append("#### Implementation")
            lines.append("")
            lines.append(str(story["implementation"]).rstrip())
            lines.append("")
            lines.append("#### Validation")
            lines.append("")
            lines.append(str(story["validation"]).rstrip())
            lines.append("")
            lines.extend(_render_footnotes(story))

    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the guide is missing or differs from fixtures",
    )
    args = parser.parse_args(argv)

    errors = validate_story_fixtures()
    if errors:
        print("story.json validation failed:", file=sys.stderr)
        for err in errors:
            print(f"  {err}", file=sys.stderr)
        return 1

    if not PERSONAS_PATH.is_file():
        print(f"missing {PERSONAS_PATH}", file=sys.stderr)
        return 1

    personas = _load_json(PERSONAS_PATH)
    stories = collect_canonical_stories()
    rendered = render_guide(stories, personas)

    if args.check:
        if not GUIDE_PATH.is_file():
            print(f"missing generated guide {GUIDE_PATH}", file=sys.stderr)
            return 1
        current = GUIDE_PATH.read_text(encoding="utf-8")
        if current != rendered:
            print(
                f"{GUIDE_PATH} is out of date; run "
                "python scripts/generate_user_stories_md.py",
                file=sys.stderr,
            )
            return 1
        print(f"ok: {GUIDE_PATH} matches fixtures ({len(stories)} stories)")
        return 0

    GUIDE_PATH.parent.mkdir(parents=True, exist_ok=True)
    GUIDE_PATH.write_text(rendered, encoding="utf-8")
    print(f"wrote {GUIDE_PATH} ({len(stories)} stories)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
